# Generated by Django 4.2 on 2025-07-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specials',
            name='content',
            field=models.TextField(default='test'),
        ),
    ]
