# Generated by Django 4.2 on 2025-07-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_specials_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='specials',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
