# Generated by Django 4.2 on 2025-06-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Pricing',
        ),
    ]
