# Generated by Django 4.2 on 2025-07-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_frequntlyquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FrequntlyQuestion',
            new_name='FrequentlyQuestion',
        ),
    ]
